"""EPSS scores, risk acceptance, and evidence attachments.

Adjusted from the autogenerated draft in two places:

* ``risk_accepted`` is NOT NULL, so it needs a ``server_default``. Without one,
  ``ADD COLUMN`` fails on any table that already has rows — which is every
  real deployment, and exactly the class of upgrade break this migration
  system exists to prevent.
* The new foreign key is named explicitly. Alembic emitted
  ``drop_constraint(None, ...)`` for the downgrade, which cannot execute.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-05
"""
from alembic import op
import sqlalchemy as sa

import backend.database

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None

FK_RISK_ACCEPTED_BY = "fk_vulnerabilities_risk_accepted_by_users"


def upgrade():
    op.create_table(
        'vulnerability_attachments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vulnerability_id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('content_type', sa.String(length=120), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('sha256', sa.String(length=64), nullable=False),
        sa.Column('storage_path', sa.String(length=500), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('uploaded_by', sa.Integer(), nullable=True),
        sa.Column('team_id', sa.Integer(), nullable=True),
        sa.Column('created_at', backend.database.TZDateTime(), nullable=False),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('vulnerability_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_attachments_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_attachments_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_attachments_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_attachments_vulnerability_id'), ['vulnerability_id'], unique=False)

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epss_score', sa.Numeric(precision=6, scale=5), nullable=True))
        batch_op.add_column(sa.Column('epss_percentile', sa.Numeric(precision=6, scale=5), nullable=True))
        batch_op.add_column(sa.Column('epss_updated_at', backend.database.TZDateTime(), nullable=True))
        # server_default is required for existing rows; the model default
        # takes over for anything inserted afterwards.
        batch_op.add_column(sa.Column('risk_accepted', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.add_column(sa.Column('risk_accepted_at', backend.database.TZDateTime(), nullable=True))
        batch_op.add_column(sa.Column('risk_accepted_until', backend.database.TZDateTime(), nullable=True))
        batch_op.add_column(sa.Column('risk_accepted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('risk_acceptance_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vulnerabilities_epss_score'), ['epss_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_risk_accepted'), ['risk_accepted'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_risk_accepted_by'), ['risk_accepted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_risk_accepted_until'), ['risk_accepted_until'], unique=False)
        batch_op.create_foreign_key(FK_RISK_ACCEPTED_BY, 'users', ['risk_accepted_by'], ['id'], ondelete='SET NULL')


def downgrade():
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_constraint(FK_RISK_ACCEPTED_BY, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_risk_accepted_until'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_risk_accepted_by'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_risk_accepted'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_epss_score'))
        batch_op.drop_column('risk_acceptance_reason')
        batch_op.drop_column('risk_accepted_by')
        batch_op.drop_column('risk_accepted_until')
        batch_op.drop_column('risk_accepted_at')
        batch_op.drop_column('risk_accepted')
        batch_op.drop_column('epss_updated_at')
        batch_op.drop_column('epss_percentile')
        batch_op.drop_column('epss_score')

    with op.batch_alter_table('vulnerability_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_attachments_vulnerability_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_attachments_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_attachments_team_id'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_attachments_sha256'))
    op.drop_table('vulnerability_attachments')
